[openstreetmap]
relation_id = 351671 # Nõmme
# Alternatives:
# way_id = 45453752
# bbox = [8.373212, 47.31758, 8.388319, 47.328053]

building_buffer = 50 # meters
simplify = 0.0001 # degrees
poi_area_buffer = 1000 # meters

[layers]
# Lists of tags (as k=v) for each layer
shops = ['shop=convenience', 'shop=supermarket']
health = ['amenity=clinic', 'amenity=hospital', 'amenity=doctors', 'amenity=pharmacy']
cafe = ['amenity=cafe', 'amenity=fast_food', 'amenity=restaurant', 'amenity=bar', 'amenity=pub']
community = ['amenity=library', 'amenity=social_centre', 'amenity=community_centre']
school = ['amenity=school', 'amenity=university', 'amenity=college']

[isochrones]
graphhopper = 'http://localhost:8989/isochrone'

# Name = [ profile name, distance in minutes]
bike = ['bike', 10]
foot = ['foot', 15]
